spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/JWT  
    username: postgres    # fill your username of database       
    password: postgres     #  fill your password of database
    driver-class-name: org.postgresql.Driver         # PostgreSQL driver class

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update        # Change to 'create' if you want to create tables on startup
    properties:
      hibernate:
        format_sql: true     # Optional: Format SQL queries for readability
        show_sql: false       # Optional: Show SQL queries in logs for debugging
env:
  jwtSecret: fb768f20b553eb5788426e96d983275382e796121f850d7ad4b2a59aa9b63b5f